package com.student.util;

import java.sql.*;

public class DatabaseInitializer {
    public static void initialize() {
        String admin = "CREATE TABLE IF NOT EXISTS admin_settings (admin_id INT PRIMARY KEY, admin_name VARCHAR(100) NOT NULL, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(100) NOT NULL)";
        String courses = "CREATE TABLE IF NOT EXISTS courses (course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, course_name VARCHAR(120) NOT NULL UNIQUE, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE')";
        String students = "CREATE TABLE IF NOT EXISTS students (student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, email VARCHAR(150) NOT NULL, phone VARCHAR(30), gender VARCHAR(30), department VARCHAR(100), city VARCHAR(100), course_id INT, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', CONSTRAINT fk_student_course FOREIGN KEY (course_id) REFERENCES courses(course_id))";
        String marks = "CREATE TABLE IF NOT EXISTS marks (mark_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id INT NOT NULL, course_id INT NOT NULL, marks DECIMAL(5,2) NOT NULL, max_marks DECIMAL(5,2) NOT NULL DEFAULT 100, remarks VARCHAR(255), CONSTRAINT fk_marks_student FOREIGN KEY (student_id) REFERENCES students(student_id), CONSTRAINT fk_marks_course FOREIGN KEY (course_id) REFERENCES courses(course_id), CONSTRAINT uq_student_course_marks UNIQUE(student_id, course_id))";
        try (Connection c = DBConnection.getConnection(); Statement s = c.createStatement()) {
            s.execute(admin); s.execute(courses); s.execute(students); s.execute(marks);
            seed(c);
        } catch (SQLException e) { throw new RuntimeException("Database initialization failed", e); }
    }

    private static void seed(Connection c) throws SQLException {
        try (PreparedStatement p = c.prepareStatement("SELECT COUNT(*) FROM admin_settings")) {
            ResultSet rs = p.executeQuery(); rs.next();
            if (rs.getInt(1) == 0) {
                try (PreparedStatement ins = c.prepareStatement("INSERT INTO admin_settings(admin_id,admin_name,username,password) VALUES(1,'Admin','admin','admin123')")) { ins.executeUpdate(); }
            }
        }
        try (PreparedStatement p = c.prepareStatement("SELECT COUNT(*) FROM courses")) {
            ResultSet rs = p.executeQuery(); rs.next();
            if (rs.getInt(1) == 0) {
                String[] names = {"Java Development", "Web Technologies", "Database Management", "Software Engineering", "Data Structures"};
                try (PreparedStatement ins = c.prepareStatement("INSERT INTO courses(course_name,status) VALUES(?, 'ACTIVE')")) {
                    for (String n : names) { ins.setString(1,n); ins.addBatch(); }
                    ins.executeBatch();
                }
            }
        }
    }
}
