/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2026-10-01 06:07:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html><head><title>Dashboard - Student Management</title><link rel=\"stylesheet\" href=\"css/style.css\"></head>\n");
      out.write("<body>\n");
      out.write("<aside class=\"sidebar\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/sidebar.jsp", out, false);
      out.write("</aside>\n");
      out.write("<main class=\"main\">\n");
      out.write("  <header class=\"topbar\">\n");
      out.write("    <div><span class=\"eyebrow\">ADMIN CONSOLE</span><h1>Dashboard</h1><p>Welcome back to your Student Management System</p></div>\n");
      out.write("    <div class=\"profile\">\n");
      out.write("      <div class=\"avatar\">");
      out.print( session.getAttribute("adminName") != null && !session.getAttribute("adminName").toString().isBlank() ? session.getAttribute("adminName").toString().substring(0,1).toUpperCase() : "A" );
      out.write("</div>\n");
      out.write("      <div><b>");
      out.print(session.getAttribute("adminName"));
      out.write("</b><small>Administrator</small></div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <section class=\"hero\">\n");
      out.write("    <div class=\"hero-content\">\n");
      out.write("      <span class=\"eyebrow\" style=\"color:#d9bd59\">STUDENT MANAGEMENT SYSTEM</span>\n");
      out.write("      <h2>Manage your academic records with ease.</h2>\n");
      out.write("      <p>Students, Courses, Marks and Results- all in one place!</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"hero-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M12 3 3 7.5l9 4.5 6.8-3.4V14h2V7.5L12 3Zm-5 10.2V17c0 2 2.2 3.5 5 3.5s5-1.5 5-3.5v-3.8l-5 2.5-5-2.5Z\"/></svg></div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <section class=\"stats\">\n");
      out.write("    <div class=\"stat\"><div class=\"stat-icon blue\"><svg viewBox=\"0 0 24 24\"><path d=\"M16 20v-1.5c0-2.2-2-4-4.5-4S7 16.3 7 18.5V20h9ZM11.5 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z\"/></svg></div><div><span>Total Students</span><strong>");
      out.print(request.getAttribute("totalStudents"));
      out.write("</strong><small>Registered students</small></div></div>\n");
      out.write("    <div class=\"stat\"><div class=\"stat-icon green\"><svg viewBox=\"0 0 24 24\"><path d=\"m9.2 16.6-4.3-4.3 1.4-1.4 2.9 2.9 8-8 1.4 1.4-9.4 9.4Z\"/></svg></div><div><span>Active Students</span><strong>");
      out.print(request.getAttribute("activeStudents"));
      out.write("</strong><small>Currently active</small></div></div>\n");
      out.write("    <div class=\"stat\"><div class=\"stat-icon red\"><svg viewBox=\"0 0 24 24\"><path d=\"M11 5h2v9h-2V5Zm0 11h2v2h-2v-2Z\"/></svg></div><div><span>Inactive Students</span><strong>");
      out.print(request.getAttribute("inactiveStudents"));
      out.write("</strong><small>Need attention</small></div></div>\n");
      out.write("    <div class=\"stat\"><div class=\"stat-icon gold\"><svg viewBox=\"0 0 24 24\"><path d=\"M4 4h6v6H4V4Zm10 0h6v6h-6V4ZM4 14h6v6H4v-6Zm10 0h6v6h-6v-6Z\"/></svg></div><div><span>Total Courses</span><strong>");
      out.print(request.getAttribute("totalCourses"));
      out.write("</strong><small>Available courses</small></div></div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <div class=\"section-heading\"><div><h2>Quick Actions</h2><p>Common academic and administrative tasks</p></div></div>\n");
      out.write("  <section class=\"quick-grid\">\n");
      out.write("    <a href=\"students\" class=\"quick\"><span class=\"quick-icon\"><svg viewBox=\"0 0 24 24\"><path d=\"M16 20v-1.5c0-2.2-2-4-4.5-4S7 16.3 7 18.5V20h9ZM11.5 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z\"/></svg></span><div><b>View All Students</b><small>Browse student records</small></div><i>→</i></a>\n");
      out.write("    <a href=\"add-student\" class=\"quick\"><span class=\"quick-icon\"><svg viewBox=\"0 0 24 24\"><path d=\"M11 5h2v6h6v2h-6v6h-2v-6H5v-2h6V5Z\"/></svg></span><div><b>Add New Student</b><small>Create a student record</small></div><i>→</i></a>\n");
      out.write("    <a href=\"marks\" class=\"quick\"><span class=\"quick-icon\"><svg viewBox=\"0 0 24 24\"><path d=\"M5 4h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Zm2 4v2h10V8H7Zm0 4v2h7v-2H7Zm0 4v1h4v-1H7Z\"/></svg></span><div><b>Enter Marks</b><small>Add or update marks</small></div><i>→</i></a>\n");
      out.write("    <a href=\"marksheet\" class=\"quick\"><span class=\"quick-icon\"><svg viewBox=\"0 0 24 24\"><path d=\"M6 3h9l4 4v14H6a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2Zm8 1.5V8h3.5L14 4.5ZM8 11h8V9H8v2Zm0 4h8v-2H8v2Zm0 4h5v-2H8v2Z\"/></svg></span><div><b>Generate Marksheet</b><small>View a student's result</small></div><i>→</i></a>\n");
      out.write("    <a href=\"courses\" class=\"quick\"><span class=\"quick-icon\"><svg viewBox=\"0 0 24 24\"><path d=\"M4 5a2 2 0 0 1 2-2h13v15H6a2 2 0 0 0-2 2V5Zm2 0v11h11V5H6Z\"/></svg></span><div><b>Manage Courses</b><small>Add academic courses</small></div><i>→</i></a>\n");
      out.write("    <a href=\"settings\" class=\"quick\"><span class=\"quick-icon\"><svg viewBox=\"0 0 24 24\"><path d=\"m19.4 13.5 1.4 1.1-2 3.4-1.7-.7c-.5.4-1 .7-1.6.9L15.2 20h-4l-.3-1.8c-.6-.2-1.1-.5-1.6-.9l-1.7.7-2-3.4L7 13.5a7 7 0 0 1 0-3L5.6 9.4l2-3.4 1.7.7c.5-.4 1-.7 1.6-.9L11.2 4h4l.3 1.8c.6.2 1.1.5 1.6.9l1.7-.7 2 3.4-1.4 1.1a7 7 0 0 1 0 3Z\"/></svg></span><div><b>Admin Settings</b><small>Profile and password</small></div><i>→</i></a>\n");
      out.write("  </section>\n");
      out.write("</main></body></html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
