/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2026-10-01 05:58:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.student.model.Student;
import com.student.model.Mark;

public final class marksheet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.student.model.Mark");
    _jspx_imports_classes.add("com.student.model.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html><html><head><title>Marksheet</title><link rel=\"stylesheet\" href=\"css/style.css\"></head><body><aside class=\"sidebar\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/sidebar.jsp", out, false);
      out.write("</aside><main class=\"main\"><header class=\"topbar\"><div><h1>Marksheet</h1><p>Generate a student's academic result</p></div></header><div class=\"panel form-panel\"><form method=\"get\" action=\"marksheet\" class=\"inline-form\"><div class=\"grow\"><label>Select Student</label><select name=\"studentId\" required><option value=\"\">Choose a student</option>");
for(Student s:(List<Student>)request.getAttribute("students")){
      out.write("<option value=\"");
      out.print(s.getStudentId());
      out.write('"');
      out.write(' ');
      out.print(request.getParameter("studentId")!=null&&request.getParameter("studentId").equals(String.valueOf(s.getStudentId()))?"selected":"");
      out.write('>');
      out.print(s.getFirstName());
      out.write(' ');
      out.print(s.getLastName());
      out.write(' ');
      out.write('(');
      out.write('#');
      out.print(s.getStudentId());
      out.write(")</option>");
}
      out.write("</select></div><button class=\"btn primary\">Generate Marksheet</button></form></div>");
if(request.getAttribute("selected")!=null){Student s=(Student)request.getAttribute("selected");
      out.write("<div class=\"marksheet\"><div class=\"marksheet-head\"><div><span class=\"eyebrow\">ACADEMIC MARKSHEET</span><h2>");
      out.print(s.getFirstName());
      out.write(' ');
      out.print(s.getLastName());
      out.write("</h2><p>");
      out.print(s.getEmail());
      out.write(' ');
      out.write('·');
      out.write(' ');
      out.print(s.getDepartment()==null?"":s.getDepartment());
      out.write(" · Student #");
      out.print(s.getStudentId());
      out.write("</p></div><div class=\"result-badge\"><b>");
      out.print(request.getAttribute("result"));
      out.write("</b><span>Grade ");
      out.print(request.getAttribute("grade"));
      out.write("</span></div></div><div class=\"table-wrap\"><table><thead><tr><th>Course</th><th>Marks Obtained</th><th>Maximum</th><th>Remarks</th></tr></thead><tbody>");
for(Mark m:(List<Mark>)request.getAttribute("marks")){
      out.write("<tr><td><b>");
      out.print(m.getCourseName());
      out.write("</b></td><td>");
      out.print(m.getMarks());
      out.write("</td><td>");
      out.print(m.getMaxMarks());
      out.write("</td><td>");
      out.print(m.getRemarks()==null?"—":m.getRemarks());
      out.write("</td></tr>");
}
      out.write("</tbody></table></div><div class=\"result-grid\"><div><span>Total</span><b>");
      out.print(request.getAttribute("total"));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(request.getAttribute("maxTotal"));
      out.write("</b></div><div><span>Percentage</span><b>");
      out.print(String.format("%.2f",(Double)request.getAttribute("percentage")));
      out.write("%</b></div><div><span>Grade</span><b>");
      out.print(request.getAttribute("grade"));
      out.write("</b></div><div><span>Result</span><b>");
      out.print(request.getAttribute("result"));
      out.write("</b></div></div></div>");
}
      out.write("</main></body></html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
