/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2026-10-01 05:58:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.student.model.Student;
import com.student.model.Course;
import com.student.model.Mark;

public final class marks_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.student.model.Course");
    _jspx_imports_classes.add("com.student.model.Mark");
    _jspx_imports_classes.add("com.student.model.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html><html><head><title>Marks</title><link rel=\"stylesheet\" href=\"css/style.css\"></head><body><aside class=\"sidebar\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/sidebar.jsp", out, false);
      out.write("</aside><main class=\"main\"><header class=\"topbar\"><div><h1>Marks</h1><p>Add or update marks for students</p></div><a class=\"btn secondary\" href=\"marksheet\">View Marksheet</a></header><div class=\"two-col\"><div class=\"panel form-panel\"><h2>Enter Marks</h2><p class=\"muted\">One student + one course = one marks record. Saving again updates it.</p>");
if(request.getParameter("success")!=null){
      out.write("<div class=\"alert success\">Marks saved successfully.</div>");
}
if(request.getAttribute("error")!=null){
      out.write("<div class=\"alert error\">");
      out.print(request.getAttribute("error"));
      out.write("</div>");
}
      out.write("<form method=\"post\" action=\"marks\"><label>Student *</label><select name=\"studentId\" required>");
for(Student s:(List<Student>)request.getAttribute("students")){
      out.write("<option value=\"");
      out.print(s.getStudentId());
      out.write('"');
      out.write('>');
      out.print(s.getFirstName());
      out.write(' ');
      out.print(s.getLastName());
      out.write(' ');
      out.write('(');
      out.write('#');
      out.print(s.getStudentId());
      out.write(")</option>");
}
      out.write("</select><label>Course *</label><select name=\"courseId\" required>");
for(Course c:(List<Course>)request.getAttribute("courses")){
      out.write("<option value=\"");
      out.print(c.getCourseId());
      out.write('"');
      out.write('>');
      out.print(c.getCourseName());
      out.write("</option>");
}
      out.write("</select><div class=\"form-grid\"><div><label>Marks *</label><input type=\"number\" step=\"0.01\" min=\"0\" name=\"marks\" required></div><div><label>Maximum Marks</label><input type=\"number\" step=\"0.01\" min=\"1\" name=\"maxMarks\" value=\"100\" required></div></div><label>Remarks</label><textarea name=\"remarks\" rows=\"3\" placeholder=\"Optional remarks\"></textarea><button class=\"btn primary full\">Save Marks</button></form></div><div class=\"panel\"><div class=\"panel-head\"><div><h2>Marks Records</h2><p>Recently stored academic marks</p></div></div><div class=\"table-wrap\"><table><thead><tr><th>Student</th><th>Course</th><th>Marks</th><th>Remarks</th></tr></thead><tbody>");
for(Mark m:(List<Mark>)request.getAttribute("marks")){
      out.write("<tr><td><b>");
      out.print(m.getStudentName());
      out.write("</b></td><td>");
      out.print(m.getCourseName());
      out.write("</td><td><b>");
      out.print(m.getMarks());
      out.write("</b> / ");
      out.print(m.getMaxMarks());
      out.write("</td><td>");
      out.print(m.getRemarks()==null||m.getRemarks().isBlank()?"—":m.getRemarks());
      out.write("</td></tr>");
}
      out.write("</tbody></table></div></div></div></main></body></html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
