/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2026-10-01 08:08:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class settings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html><html><head><title>Settings</title><link rel=\"stylesheet\" href=\"css/style.css\"></head><body><aside class=\"sidebar\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/sidebar.jsp", out, false);
      out.write("</aside><main class=\"main\"><header class=\"topbar\"><div><h1>Settings</h1><p>Manage administrator profile and account credentials</p></div></header><div class=\"two-col\"><div class=\"panel form-panel\"><div class=\"settings-title\"><div class=\"avatar big\">M</div><div><h2>Administrator Profile</h2><p class=\"muted\">These details appear across the admin portal.</p></div></div>");
if(request.getParameter("success")!=null){
      out.write("<div class=\"alert success\">Settings updated successfully.</div>");
}
if(request.getAttribute("error")!=null){
      out.write("<div class=\"alert error\">");
      out.print(request.getAttribute("error"));
      out.write("</div>");
}
      out.write("<form method=\"post\" action=\"settings\"><label>Admin Display Name *</label><input name=\"adminName\" value=\"");
      out.print(request.getAttribute("adminName"));
      out.write("\" required><label>Username *</label><input name=\"username\" value=\"");
      out.print(request.getAttribute("username"));
      out.write("\" required><label>New Password</label><input type=\"password\" name=\"password\" placeholder=\"Leave blank to keep current password\"><label>Confirm New Password</label><input type=\"password\" name=\"confirmPassword\" placeholder=\"Repeat new password\"><button class=\"btn primary full\">Save Settings</button></form></div><div class=\"panel\"><h2>Account & Security</h2><div class=\"security-item\"><span class=\"security-icon\">👤</span><div><b>Administrator Account</b><small>Controls access to the dashboard.</small></div><span class=\"status active\">ENABLED</span></div><div class=\"security-item\"><span class=\"security-icon\">🔑</span><div><b>Password Protection</b><small>Change the password whenever required.</small></div></div><div class=\"security-item\"><span class=\"security-icon\">🌐</span><div><b>Public Registration</b><small>Available separately without admin access.</small></div></div><div class=\"notice\"><b>Prototype note:</b> Passwords are stored plainly in this learning project. A production system should use secure password hashing, sessions with stronger controls, CSRF protection and proper authorization.</div></div></div></main></body></html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
