/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2026-10-01 05:56:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"logo\">\n");
      out.write("  <span class=\"logo-mark\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M12 3 4 7l8 4 6-3v5h2V7L12 3Zm-5 8.5V15c0 2.1 2.2 3.5 5 3.5s5-1.4 5-3.5v-3.5l-5 2.5-5-2.5Z\"/></svg></span>\n");
      out.write("  <span>Student<br>Management</span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"nav-label\">MAIN</div>\n");
      out.write("<a class=\"nav\" href=\"dashboard\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M4 10.5 12 4l8 6.5V20h-6v-5h-4v5H4v-9.5Z\"/></svg></span><span>Dashboard</span></a>\n");
      out.write("<a class=\"nav\" href=\"students\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M16 20v-1.5c0-2.2-2-4-4.5-4S7 16.3 7 18.5V20h9ZM11.5 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm7.2 7.8v-1.1c0-1.7-1-3.2-2.6-4.1.6-.2 1.2-.3 1.9-.3 2.2 0 4 1.5 4 3.4V20h-3.3Z\"/></svg></span><span>Students</span></a>\n");
      out.write("<a class=\"nav\" href=\"add-student\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M11 5h2v6h6v2h-6v6h-2v-6H5v-2h6V5Z\"/></svg></span><span>Add Student</span></a>\n");
      out.write("\n");
      out.write("<div class=\"nav-label\">ACADEMICS</div>\n");
      out.write("<a class=\"nav\" href=\"marks\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M5 4h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Zm2 4v2h10V8H7Zm0 4v2h7v-2H7Zm0 4v1h4v-1H7Z\"/></svg></span><span>Marks</span></a>\n");
      out.write("<a class=\"nav\" href=\"marksheet\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M6 3h9l4 4v14H6a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2Zm8 1.5V8h3.5L14 4.5ZM8 11h8V9H8v2Zm0 4h8v-2H8v2Zm0 4h5v-2H8v2Z\"/></svg></span><span>Marksheet</span></a>\n");
      out.write("<a class=\"nav\" href=\"courses\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M4 5a2 2 0 0 1 2-2h13v15H6a2 2 0 0 0-2 2V5Zm2 0v11h11V5H6Zm-2 15c0-1.1.9-2 2-2h13v2H6a2 2 0 0 1-2 2v-2Z\"/></svg></span><span>Courses</span></a>\n");
      out.write("\n");
      out.write("<div class=\"nav-label\">MANAGEMENT</div>\n");
      out.write("<a class=\"nav\" href=\"register-student\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M12 2a7 7 0 0 1 7 7c0 4.8-7 13-7 13S5 13.8 5 9a7 7 0 0 1 7-7Zm0 10.2A3.2 3.2 0 1 0 12 5.8a3.2 3.2 0 0 0 0 6.4Z\"/></svg></span><span>Public Registration</span></a>\n");
      out.write("<a class=\"nav\" href=\"reports\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M4 19h16v2H4a2 2 0 0 1-2-2V5h2v14Zm3-3h3V9H7v7Zm5 0h3V5h-3v11Zm5 0h3v-8h-3v8Z\"/></svg></span><span>Reports</span></a>\n");
      out.write("<a class=\"nav\" href=\"settings\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"m19.4 13.5 1.4 1.1-2 3.4-1.7-.7c-.5.4-1 .7-1.6.9L15.2 20h-4l-.3-1.8c-.6-.2-1.1-.5-1.6-.9l-1.7.7-2-3.4L7 13.5a7 7 0 0 1 0-3L5.6 9.4l2-3.4 1.7.7c.5-.4 1-.7 1.6-.9L11.2 4h4l.3 1.8c.6.2 1.1.5 1.6.9l1.7-.7 2 3.4-1.4 1.1a7 7 0 0 1 0 3ZM13.2 15.5A3.5 3.5 0 1 0 13.2 8a3.5 3.5 0 0 0 0 7.5Z\"/></svg></span><span>Settings</span></a>\n");
      out.write("\n");
      out.write("<div class=\"sidebar-bottom\">\n");
      out.write("  <div class=\"admin-mini\">\n");
      out.write("    <div class=\"avatar\">");
      out.print( session.getAttribute("adminName") != null && !session.getAttribute("adminName").toString().isBlank() ? session.getAttribute("adminName").toString().substring(0,1).toUpperCase() : "A" );
      out.write("</div>\n");
      out.write("    <div><b>");
      out.print(session.getAttribute("adminName"));
      out.write("</b><small>Administrator</small></div>\n");
      out.write("  </div>\n");
      out.write("  <a class=\"nav logout\" href=\"logout\"><span class=\"nav-icon\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\"><path d=\"M10 4h8a2 2 0 0 1 2 2v3h-2V6h-8v12h8v-3h2v3a2 2 0 0 1-2 2h-8a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Zm1.5 6 1.4 1.4L11.7 13H21v2h-9.3l1.2 1.6-1.4 1.4-3.5-4 3.5-4Z\"/></svg></span><span>Logout</span></a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function(){var path=window.location.pathname.split('/').pop()||'dashboard';document.querySelectorAll('.sidebar a.nav').forEach(function(a){var href=(a.getAttribute('href')||'').split('/').pop();if(href===path){a.classList.add('active');}})})();\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
